# -*- coding: utf-8 -*-
"""Text_Cleanup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Wa5lJbmpLpBOzPAGVOldbIiKyCbzXsT
"""

def Cleanup(mapping):
  import re
  for key, captions in mapping.items():
    for i in range(len(captions)):
      #take one cations at a time
      caption=captions[i]
      #convert to lowercase
      caption=caption.lower()
      #deleate digits,special chars
      caption=caption.replace('[^A-Za-z]', '')
      #delete addinional spaces
      caption=caption.replace('\s+', ' ')
      #Remove punctuations
      caption = re.sub(r'[^\w\s]', '', caption)
      #add start and end tags to the cation
      caption='startseq '+ ' '.join([word for word in caption.split() if len(word)>1]) +' endseq'
      captions[i]=caption
  return